language: python
arch: 
 - ppc64le
 - amd64
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "nightly"
install:
 - pip install coverage
 - pip install backports.lzma
 - ./setup.py install
script: ./setup.py test
cache: pip
matrix:
  allow_failures:
   - python: nightly
